name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 5.18.9
          run_install: true

      - run: pnpm lint

  test:
    name: Node Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 5.18.9
          run_install: true

      - run: pnpm test:node

  ember-try-scenarios:
    name: Ember Tests (${{ matrix.test-suite }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-suite:
          - test:strip
          - test:keep

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 5.18.9
          run_install: true

      - run: pnpm test:all -- --skip-cleanup
        env:
          TEST_SUITE: ${{ matrix.test-suite }}
